from ex1.factory import HealingCreatureFactory, TransformCreatureFactory


if __name__ == "__main__":
    heal_factory = HealingCreatureFactory()
    heal_creature = heal_factory.create_base()
    evolved_heal_creature = heal_factory.create_evolved()
    print("Testing Creature with healing capability")
    print(" base:")
    print(heal_creature.describe())
    print(heal_creature.attack())
    print(heal_creature.heal())
    print(" evolved:")
    print(evolved_heal_creature.describe())
    print(evolved_heal_creature.attack())
    print(evolved_heal_creature.heal())
    print()

    transform_factory = TransformCreatureFactory()
    transform_creature = transform_factory.create_base()
    evolved_transform_creature = transform_factory.create_evolved()
    print("Testing Creature with transform capability")
    print(" base:")
    print(transform_creature.describe())
    print(transform_creature.attack())
    print(transform_creature.transform())
    print(transform_creature.attack())
    print(transform_creature.revert())
    print(" evolved:")
    print(evolved_transform_creature.describe())
    print(evolved_transform_creature.attack())
    print(evolved_transform_creature.transform())
    print(evolved_transform_creature.attack())
    print(evolved_transform_creature.revert())
